dist: xenial
sudo: required
language: cpp

addons:
    apt:
        sources:
            - sourceline: 'ppa:beineri/opt-qt-5.12.1-xenial'
            - sourceline: 'ppa:jonathonf/vlc-3'

        packages:
            - libboost-dev
            - libmpg123-dev
            - libsdl2-dev
            - libsndfile1-dev
            - libvlc-dev
            - qt512base

    homebrew:
        packages:
            - glib
            - libsndfile
            - mpg123
            - qt5
            - sdl2

matrix:
    include:
        - os: linux
          compiler: gcc

        - os: osx
          compiler: clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        source /opt/qt512/bin/qt512-env.sh;
      fi

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew link qt5 --force;
      fi

    - sudo ln -s /usr/local/lib /usr/local/lib64;

    #
    # Install libADLMIDI
    #
    - cd "$HOME"
    - wget 'https://github.com/Wohlstand/libADLMIDI/archive/c19bf11f4b12004051fc76651733e17f3e98143a.tar.gz'
        -O adlmidi.tar.gz
    - tar xf adlmidi.tar.gz
    - cd libADLMIDI-c19bf11f4b12004051fc76651733e17f3e98143a
    - mkdir build
    - cd build
    - cmake
        -DlibADLMIDI_SHARED=on
        -DlibADLMIDI_STATIC=off
        -DEXAMPLE_SDL2_AUDIO=off
        ..
    - make -j2
    - sudo make install

    #
    # Install fluidsynth
    #
    - cd "$HOME"
    - wget 'https://github.com/FluidSynth/fluidsynth/archive/v2.0.4.tar.gz'
    - tar xf 'v2.0.4.tar.gz'
    - cd fluidsynth-2.0.4
    - mkdir build
    - cd build
    - cmake -Denable-framework=off ..
    - make -j2
    - sudo make install

    #
    # Install libopenmpt
    #
    - cd "$HOME"
    - wget 'https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.4.3+release.autotools.tar.gz'
    - tar xf 'libopenmpt-0.4.3+release.autotools.tar.gz'
    - mkdir openmpt-build
    - cd openmpt-build
    - ../libopenmpt-0.4.3+release.autotools/configure
        --enable-silent-rules
        --disable-dependency-tracking
        --enable-shared
        --disable-static
        --disable-openmpt123
        --disable-examples
        --disable-tests
        --disable-doxygen-doc
        --without-zlib
        --without-mpg123
        --without-ogg
        --without-vorbis
        --without-vorbisfile
        --without-pulseaudio
        --without-portaudio
        --without-portaudiocpp
        --without-sdl2
        --without-sdl
        --without-sndfile
        --without-flac
    - make -j2
    - sudo make install

before_script:
    - qmake -version
    - cd "$TRAVIS_BUILD_DIR"/..
    - mkdir build
    - cd build

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        qmake -config disable-video -config adlmidi "$TRAVIS_BUILD_DIR";
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        qmake -config adlmidi "$TRAVIS_BUILD_DIR";
      fi
    - make -j2
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo make install;
      fi
