name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    strategy:
      matrix:
        docker_image: ['realnc/hugor-build:linux-x86', 'realnc/hugor-build:linux-x64']

    runs-on: ubuntu-latest
    container: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        qmake
        make appimage

  build-macos:
    runs-on: macos-10.15
    env:
      ADLMIDI_VERSION: 1.5.0.1-1
      CMAKE_GENERATOR: Ninja

    steps:
    - name: Install deps
      run: |
        brew install \
          fluidsynth \
          glib \
          libopenmpt \
          libsndfile \
          mpg123 \
          ninja \
          pkg-config \
          qt5 \
          sdl2
        brew link qt5 --force

    - name: Build libADLMIDI
      working-directory: ../
      run: |
        wget -nv "https://github.com/Wohlstand/libADLMIDI/archive/v${ADLMIDI_VERSION}.tar.gz" -O- | tar xz
        cd "libADLMIDI-${ADLMIDI_VERSION}"
        mkdir build
        cd build
        cmake \
          -DlibADLMIDI_SHARED=on \
          -DlibADLMIDI_STATIC=off \
          -DEXAMPLE_SDL2_AUDIO=off \
          ..
        sudo cmake --build . --target install -v

    - uses: actions/checkout@v2

    - name: Build
      run: |
        qmake -config disable-video -config adlmidi
        make -j`sysctl -n hw.ncpu`
